apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: server
          image: postgres:latest
          args:
          - postgres
          - -c
          - wal_level=logical
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: debeziumdb
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: initdb
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: sql-setup
