apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: server
          image: mysql:latest
          # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
          # (this is just an example, not intended to be a production configuration)
          args:
          - --default-authentication-plugin=mysql_native_password
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: gingersnap_user
            - name: MYSQL_PASSWORD
              value: password
          volumeMounts:
            - name: initdb
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: sql-setup
