
FROM registry.access.redhat.com/ubi8/openjdk-17-runtime

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/*runner.jar /deployments/db-syncer.jar

USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/db-syncer.jar"