name: Publish dev images to quay.io

on:
  push:
    branches:
      - 'main'

jobs:
  image:
    uses: ./.github/workflows/build-image.yaml

  upload:
    needs: image
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Load and Push image
        # Use same tag value as passed to image job
        run: |
          docker load --input ${{ needs.image.outputs.image-name }}
          docker push quay.io/gingersnap/db-syncer:latest
